name: Build and Deploy to CloudBase

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Tencent Container Registry
      uses: docker/login-action@v2
      with:
        registry: ccr.ccs.tencentcloudapi.com
        username: ${{ secrets.TCR_USERNAME }}
        password: ${{ secrets.TCR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ccr.ccs.tencentcloudapi.com/yundong/backend:latest
          ccr.ccs.tencentcloudapi.com/yundong/backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 